# Название итоговой программы
TARGET = program

# Компилятор
CXX = g++

# Флаги компилятора
CXXFLAGS = -Wall -Wextra -O2

# Исходники
SRC = main.cpp

# Цель по умолчанию (сборка)
all:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

# Очистка 
clean: 
	rm -f $(TARGET)
